---

port: 3000

log: core
logger: file
log_path: .

plugins:
    'RPC::RESTRPC':
        '/metacpan':
            'Example::API::MetaCpan':
                search: mc_search
    'RPC::JSONRPC':
        '/metacpan':
            'Example::API::MetaCpan':
                rpc_search: mc_search
    'RPC::XMLRPC':
        '/metacpan':
            'Example::API::MetaCpan':
                'rpc.search': mc_search

metacpan:
    base_uri: https://fastapi.metacpan.org/v1/release/_search
